pipeline {
    agent {label 'slave-python'}
    
    stages {
        
        stage('pull') {
            steps {
                retry(3){
                    timeout(time:10,unit:'SECONDS'){
                        git branch: 'develop', credentialsId: 'ssh_key', url: 'git@git.nju.edu.cn:monian/backend-collect.git'
                    }
                }
                sh 'pwd'
                sh 'ls -al'
            }
        }   
        
        stage('clean') {
            steps {
                sh 'make clean'
            }
        }
        
        stage('build') {
            steps {
                sh 'make build'
            }
        }
        
        stage('test') {
            steps {
				script{
                    try{
                        sh 'make test'
						jacoco()
                    }catch(err){
                        sh 'make deploy'
                        throw err
                    }
                }
            }
        }
        
        stage('deploy') {
            steps {
                sh 'make deploy'
            }
        }
        
    }
	post {
		success {
			updateGitlabCommitStatus name: 'CICD', state: 'success'
		}
		failure {
            updateGitlabCommitStatus name: 'CICD', state: 'failed'
        }
    }
        
    
}
